### ISSUE TITLE
mame.bigode.net is down

### ISSUE THREAD

**Issue by Chinoforest** [pdrb/mamescraper#1]
Hi. I've just found your script. Is working great with ADB but I wanted to warn you that http://mame.bigode.net/ is down, so maybe you should change to ADB by default.

Also, does it warns you about the roms that weren't scraped? I mean, the ones that weren't found on the database so there's not image or information.

Thanks
Gonzalo

**Comment by pdrb** [comment]
Hi! It was probably just a temporary network problem, it is working fine now.

Bigode ("mame.bigode.net") is the default source because it is maintained by me and is a lot faster than adb.

About the missing games, the answer is yes, the program shows you a list of the games not found on the database.
